name: 3dgstream_viewer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
    - cuda-python
    - cmake
    - glfw
    - PyGLM
    - imgui
    - PyOpenGL
    - numpy
    - imageio
    - submodules/diff-gaussian-rasterization
